# Generated by Django 6.0.3 on 2026-03-24 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='ชื่อหัวข้องาน')),
                ('category', models.CharField(max_length=100, verbose_name='ประเภทงาน')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='กำหนดส่ง')),
                ('priority', models.IntegerField(choices=[(3, 'ด่วนมาก'), (2, 'ปกติ'), (1, 'ไม่เร่งด่วน')], default=2, verbose_name='ความเร่งด่วน')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('done', 'Done')], default='todo', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่เสร็จงาน')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของงาน')),
            ],
            options={
                'verbose_name': 'งาน',
                'verbose_name_plural': 'รายการงานทั้งหมด',
                'ordering': ['-priority', 'deadline'],
            },
        ),
    ]
