# Generated by Django 6.0.3 on 2026-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('pending', 'Pending'), ('done', 'Done')], default='todo', max_length=20, verbose_name='สถานะ'),
        ),
    ]
